# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Giovanni Orlando 👑 (@giovanni0918)
author: Giovanni Orlando
email: gorlandor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio Website for Giovanni Orlando, Powered by Jekyll. Computer Engineer • Food Lover • Tech Enthusiast • https://giovanni-orlando.com • @giovanni0918
baseurl: "" # the subpath of your site, e.g. /blog
url: https://giovanni-orlando.com
enforce_ssl: giovanni-orlando.com
repository: giovanni0918/giovanni0918.github.io
google_analytics: UA-82693415-1 
permalink: /:categories/:title
profiles:
 - account: facebook
   username: giovanni0918
 - account: github
   username: giovanni0918
 - account: google
   username: +giovanniorlandoi7
 - account: instagram
   username: giovanni0918
 - account: linkedin
   username: in/giovanni-orlando
 - account: medium
   username: giovanni0918
 - account: pinterest
   username: giovanniorlando
 - account: tumblr
   username: giovanni0918
 - account: twitter
   username: giovanni0918
 - account: youtube
   username: giovanniorlandoi7

tabs: 
 - title: Home
   url: /

 - title: Twitter
   url: /pages/twitter/

 - title: Blog
   url: /pages/blog/

 - title: Contact
   url: /pages/contact/

 - title: Services
   url: /pages/services/

github: [metadata]
# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-timeago
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules